version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./docker-entrypoint.sh
  db:
    image: "postgres:alpine"
    env_file: .create_db