"""empty message

Revision ID: 630eb762db82
Revises: 905e10f28487
Create Date: 2020-08-13 13:45:55.657800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630eb762db82'
down_revision = '905e10f28487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_users', sa.Column('github_email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_users', 'github_email')
    # ### end Alembic commands ###
